name: Meredithpetrickphotography
favicon: null
layout_spectrum: 0.11621
typography_spectrum: 0.11406
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f7f6'
    - '#e0d4ca'
    - '#aeb0b4'
    - '#dbdfe4'
    - '#c7cbd1'
  brandStrength: 0.125
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
