title: Meredith Petrick Photography
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.125
  brandStrength: 0.6875
  rhythmicContrast: 0.5
  brandColors:
    - '#f7f7f6'
    - '#e0d4ca'
    - '#aeb0b4'
    - '#dbdfe4'
    - '#c7cbd1'
  lightness: 0.875
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Meredithpetrickphotography
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9964158
layout_spectrum: 1
