name: Meredithpetrickphotography
favicon: null
layout_spectrum: 0.11621
typography_spectrum: 0.11406
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#afb2b5'
    - '#be091c'
    - '#333333'
    - '#fc58a2'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
