name: Meredithpetrickphotography
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: Meredith Petrick Photography
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: 'http://meredithpetrickphotography.com'
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f7f6'
    - '#e0d4ca'
    - '#aeb0b4'
    - '#dbdfe4'
    - '#c7cbd1'
  brandStrength: 0.6875
  lightness: 0.875
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
